version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 5s
      retries: 5
      timeout: 5s

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/29092"]
      interval: 5s
      retries: 5
      timeout: 5s

  data_production:
    build: ./data_production
    container_name: data_production
    depends_on:
      broker:
        condition: service_healthy
    environment:
      KAFKA_BROKER: "broker:29092"
    ports:
      - "5000:5000"
    entrypoint: ["./wait-for-kafka.sh", "broker:29092", "python", "server.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/bot_event"]
      interval: 5s
      retries: 5
      timeout: 3s

  data_consumer:
    build: ./data_consumer
    container_name: data_consumer
    depends_on:
      broker:
        condition: service_healthy
    environment:
      KAFKA_BROKER: "broker:29092"
    volumes:
      - ./data_consumer/data:/app/data
    entrypoint: ["./wait-for-kafka.sh", "broker:29092", "python", "consumer.py"]

  k6:
    build: ./k6
    container_name: k6
    depends_on:
      data_production:
        condition: service_healthy
    volumes:
      - ./k6:/scripts
    entrypoint: ["/scripts/wait-for-flask.sh", "data_production:5000", "k6", "run", "/scripts/bot_traffic.js"]

